// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/alert_priority_simple_type.proto
// Protobuf Java Version: 4.26.1

package uk.gov.gchq.event_logging.v4;

public final class AlertPrioritySimpleTypeProto {
  private AlertPrioritySimpleTypeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      AlertPrioritySimpleTypeProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1event_logging/v4/alert_priority_simple" +
      "_type.proto\022\020event_logging.v4\032\033buf/valid" +
      "ate/validate.proto*\253\002\n\027AlertPrioritySimp" +
      "leType\022*\n&ALERT_PRIORITY_SIMPLE_TYPE_UNS" +
      "PECIFIED\020\000\022#\n\037ALERT_PRIORITY_SIMPLE_TYPE" +
      "_NONE\020\001\022\"\n\036ALERT_PRIORITY_SIMPLE_TYPE_LO" +
      "W\020\002\022%\n!ALERT_PRIORITY_SIMPLE_TYPE_NORMAL" +
      "\020\003\022#\n\037ALERT_PRIORITY_SIMPLE_TYPE_HIGH\020\004\022" +
      "%\n!ALERT_PRIORITY_SIMPLE_TYPE_URGENT\020\005\022(" +
      "\n$ALERT_PRIORITY_SIMPLE_TYPE_IMMEDIATE\020\006" +
      "B\340\001\n\034uk.gov.gchq.event_logging.v4B\034Alert" +
      "PrioritySimpleTypeProtoP\001ZEgithub.com/gc" +
      "hq/event-logging-schema/event_logging/v4" +
      ";event_loggingv4\242\002\003EXX\252\002\017EventLogging.V4" +
      "\312\002\017EventLogging\\V4\342\002\033EventLogging\\V4\\GPB" +
      "Metadata\352\002\020EventLogging::V4b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    descriptor.resolveAllFeaturesImmutable();
    build.buf.validate.ValidateProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
