// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/authenticate_complex_type.proto
// Protobuf Java Version: 4.26.1

package uk.gov.gchq.event_logging.v4;

public final class AuthenticateComplexTypeProto {
  private AuthenticateComplexTypeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      AuthenticateComplexTypeProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_logging_v4_AuthenticateComplexType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_event_logging_v4_AuthenticateComplexType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0event_logging/v4/authenticate_complex_" +
      "type.proto\022\020event_logging.v4\0326event_logg" +
      "ing/v4/authenticate_action_simple_type.p" +
      "roto\032:event_logging/v4/authenticate_logo" +
      "n_type_simple_type.proto\0328event_logging/" +
      "v4/authenticate_outcome_complex_type.pro" +
      "to\032(event_logging/v4/data_complex_type.p" +
      "roto\032*event_logging/v4/device_complex_ty" +
      "pe.proto\032(event_logging/v4/user_complex_" +
      "type.proto\032\033buf/validate/validate.proto\"" +
      "\230\004\n\027AuthenticateComplexType\022N\n\006action\030\001 " +
      "\001(\0162..event_logging.v4.AuthenticateActio" +
      "nSimpleTypeB\006\272H\003\310\001\001R\006action\022Z\n\nlogon_typ" +
      "e\030\002 \001(\01621.event_logging.v4.AuthenticateL" +
      "ogonTypeSimpleTypeB\010\272H\005\202\001\002\020\001R\tlogonType\022" +
      "=\n\004user\030\003 \001(\0132!.event_logging.v4.UserCom" +
      "plexTypeB\006\272H\003\310\001\001R\004user\022C\n\006device\030\004 \001(\0132#" +
      ".event_logging.v4.DeviceComplexTypeB\006\272H\003" +
      "\310\001\001R\006device\022@\n\005group\030\005 \001(\0132\".event_loggi" +
      "ng.v4.GroupComplexTypeB\006\272H\003\310\001\001R\005group\022J\n" +
      "\007outcome\030\013 \001(\01320.event_logging.v4.Authen" +
      "ticateOutcomeComplexTypeR\007outcome\022?\n\004dat" +
      "a\030\014 \003(\0132!.event_logging.v4.DataComplexTy" +
      "peB\010\272H\005\222\001\002\010\000R\004dataB\340\001\n\034uk.gov.gchq.event" +
      "_logging.v4B\034AuthenticateComplexTypeProt" +
      "oP\001ZEgithub.com/gchq/event-logging-schem" +
      "a/event_logging/v4;event_loggingv4\242\002\003EXX" +
      "\252\002\017EventLogging.V4\312\002\017EventLogging\\V4\342\002\033E" +
      "ventLogging\\V4\\GPBMetadata\352\002\020EventLoggin" +
      "g::V4b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          uk.gov.gchq.event_logging.v4.AuthenticateActionSimpleTypeProto.getDescriptor(),
          uk.gov.gchq.event_logging.v4.AuthenticateLogonTypeSimpleTypeProto.getDescriptor(),
          uk.gov.gchq.event_logging.v4.AuthenticateOutcomeComplexTypeProto.getDescriptor(),
          uk.gov.gchq.event_logging.v4.DataComplexTypeProto.getDescriptor(),
          uk.gov.gchq.event_logging.v4.DeviceComplexTypeProto.getDescriptor(),
          uk.gov.gchq.event_logging.v4.UserComplexTypeProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_event_logging_v4_AuthenticateComplexType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_logging_v4_AuthenticateComplexType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_event_logging_v4_AuthenticateComplexType_descriptor,
        new java.lang.String[] { "Action", "LogonType", "User", "Device", "Group", "Outcome", "Data", });
    descriptor.resolveAllFeaturesImmutable();
    uk.gov.gchq.event_logging.v4.AuthenticateActionSimpleTypeProto.getDescriptor();
    uk.gov.gchq.event_logging.v4.AuthenticateLogonTypeSimpleTypeProto.getDescriptor();
    uk.gov.gchq.event_logging.v4.AuthenticateOutcomeComplexTypeProto.getDescriptor();
    uk.gov.gchq.event_logging.v4.DataComplexTypeProto.getDescriptor();
    uk.gov.gchq.event_logging.v4.DeviceComplexTypeProto.getDescriptor();
    uk.gov.gchq.event_logging.v4.UserComplexTypeProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
