// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/event_chain_complex_type.proto

// Protobuf Java Version: 4.26.1
package uk.gov.gchq.event_logging.v4;

public interface EventChainComplexTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event_logging.v4.EventChainComplexType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The event that this event has a relationship to or is referenced by.
   * </pre>
   *
   * <code>.event_logging.v4.ActivityComplexType activity = 1 [json_name = "activity", (.buf.validate.field) = { ... }</code>
   * @return Whether the activity field is set.
   */
  boolean hasActivity();
  /**
   * <pre>
   * The event that this event has a relationship to or is referenced by.
   * </pre>
   *
   * <code>.event_logging.v4.ActivityComplexType activity = 1 [json_name = "activity", (.buf.validate.field) = { ... }</code>
   * @return The activity.
   */
  uk.gov.gchq.event_logging.v4.ActivityComplexType getActivity();
  /**
   * <pre>
   * The event that this event has a relationship to or is referenced by.
   * </pre>
   *
   * <code>.event_logging.v4.ActivityComplexType activity = 1 [json_name = "activity", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.ActivityComplexTypeOrBuilder getActivityOrBuilder();
}
