// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/event_time_complex_type.proto

// Protobuf Java Version: 4.26.1
package uk.gov.gchq.event_logging.v4;

public interface EventTimeComplexTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event_logging.v4.EventTimeComplexType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * This element contains information about the time the event was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time_created = 1 [json_name = "timeCreated", (.buf.validate.field) = { ... }</code>
   * @return Whether the timeCreated field is set.
   */
  boolean hasTimeCreated();
  /**
   * <pre>
   * This element contains information about the time the event was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time_created = 1 [json_name = "timeCreated", (.buf.validate.field) = { ... }</code>
   * @return The timeCreated.
   */
  com.google.protobuf.Timestamp getTimeCreated();
  /**
   * <pre>
   * This element contains information about the time the event was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time_created = 1 [json_name = "timeCreated", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeCreatedOrBuilder();

  /**
   * <pre>
   * This is an optional element to be used to indicate the time source that the event creation time has been synchronised with. In most circumstances it is assumed that the event time has been synchronised with the corporate time service where the generating device resides so the inclusion of this element is not required.
   * </pre>
   *
   * <code>.event_logging.v4.DeviceComplexType time_source = 2 [json_name = "timeSource"];</code>
   * @return Whether the timeSource field is set.
   */
  boolean hasTimeSource();
  /**
   * <pre>
   * This is an optional element to be used to indicate the time source that the event creation time has been synchronised with. In most circumstances it is assumed that the event time has been synchronised with the corporate time service where the generating device resides so the inclusion of this element is not required.
   * </pre>
   *
   * <code>.event_logging.v4.DeviceComplexType time_source = 2 [json_name = "timeSource"];</code>
   * @return The timeSource.
   */
  uk.gov.gchq.event_logging.v4.DeviceComplexType getTimeSource();
  /**
   * <pre>
   * This is an optional element to be used to indicate the time source that the event creation time has been synchronised with. In most circumstances it is assumed that the event time has been synchronised with the corporate time service where the generating device resides so the inclusion of this element is not required.
   * </pre>
   *
   * <code>.event_logging.v4.DeviceComplexType time_source = 2 [json_name = "timeSource"];</code>
   */
  uk.gov.gchq.event_logging.v4.DeviceComplexTypeOrBuilder getTimeSourceOrBuilder();
}
