// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/media_complex_type.proto
// Protobuf Java Version: 4.26.1

package uk.gov.gchq.event_logging.v4;

public final class MediaComplexTypeProto {
  private MediaComplexTypeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      MediaComplexTypeProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_logging_v4_MediaComplexType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_event_logging_v4_MediaComplexType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)event_logging/v4/media_complex_type.pr" +
      "oto\022\020event_logging.v4\0322event_logging/v4/" +
      "classification_complex_type.proto\032(event" +
      "_logging/v4/data_complex_type.proto\032-eve" +
      "nt_logging/v4/media_type_simple_type.pro" +
      "to\032\033buf/validate/validate.proto\"\361\002\n\020Medi" +
      "aComplexType\022A\n\004type\030\001 \001(\0162%.event_loggi" +
      "ng.v4.MediaTypeSimpleTypeB\006\272H\003\310\001\001R\004type\022" +
      "\016\n\002id\030\002 \001(\tR\002id\022\022\n\004name\030\003 \001(\tR\004name\022\034\n\tr" +
      "emovable\030\004 \001(\010R\tremovable\022\035\n\nread_write\030" +
      "\005 \001(\010R\treadWrite\022#\n\010capacity\030\006 \001(\rB\007\272H\004*" +
      "\002 \000R\010capacity\022S\n\016classification\030\007 \001(\0132+." +
      "event_logging.v4.ClassificationComplexTy" +
      "peR\016classification\022?\n\004data\030\010 \003(\0132!.event" +
      "_logging.v4.DataComplexTypeB\010\272H\005\222\001\002\010\000R\004d" +
      "ataB\331\001\n\034uk.gov.gchq.event_logging.v4B\025Me" +
      "diaComplexTypeProtoP\001ZEgithub.com/gchq/e" +
      "vent-logging-schema/event_logging/v4;eve" +
      "nt_loggingv4\242\002\003EXX\252\002\017EventLogging.V4\312\002\017E" +
      "ventLogging\\V4\342\002\033EventLogging\\V4\\GPBMeta" +
      "data\352\002\020EventLogging::V4b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          uk.gov.gchq.event_logging.v4.ClassificationComplexTypeProto.getDescriptor(),
          uk.gov.gchq.event_logging.v4.DataComplexTypeProto.getDescriptor(),
          uk.gov.gchq.event_logging.v4.MediaTypeSimpleTypeProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_event_logging_v4_MediaComplexType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_logging_v4_MediaComplexType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_event_logging_v4_MediaComplexType_descriptor,
        new java.lang.String[] { "Type", "Id", "Name", "Removable", "ReadWrite", "Capacity", "Classification", "Data", });
    descriptor.resolveAllFeaturesImmutable();
    uk.gov.gchq.event_logging.v4.ClassificationComplexTypeProto.getDescriptor();
    uk.gov.gchq.event_logging.v4.DataComplexTypeProto.getDescriptor();
    uk.gov.gchq.event_logging.v4.MediaTypeSimpleTypeProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
