// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/network_outcome_complex_type.proto
// Protobuf Java Version: 4.26.1

package uk.gov.gchq.event_logging.v4;

public final class NetworkOutcomeComplexTypeProto {
  private NetworkOutcomeComplexTypeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      NetworkOutcomeComplexTypeProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_logging_v4_NetworkOutcomeComplexType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_event_logging_v4_NetworkOutcomeComplexType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3event_logging/v4/network_outcome_compl" +
      "ex_type.proto\022\020event_logging.v4\032(event_l" +
      "ogging/v4/data_complex_type.proto\0320event" +
      "_logging/v4/multi_object_complex_type.pr" +
      "oto\0324event_logging/v4/network_location_c" +
      "omplex_type.proto\032+event_logging/v4/outc" +
      "ome_complex_type.proto\032\033buf/validate/val" +
      "idate.proto\"\265\003\n\031NetworkOutcomeComplexTyp" +
      "e\022L\n\006source\030\001 \001(\0132,.event_logging.v4.Net" +
      "workLocationComplexTypeB\006\272H\003\310\001\001R\006source\022" +
      "N\n\013destination\030\002 \001(\0132,.event_logging.v4." +
      "NetworkLocationComplexTypeR\013destination\022" +
      "!\n\014process_name\030\003 \001(\tR\013processName\022B\n\007pa" +
      "yload\030\004 \001(\0132(.event_logging.v4.MultiObje" +
      "ctComplexTypeR\007payload\022\022\n\004rule\030\005 \001(\tR\004ru" +
      "le\022>\n\007outcome\030\006 \001(\0132$.event_logging.v4.O" +
      "utcomeComplexTypeR\007outcome\022?\n\004data\030\007 \003(\013" +
      "2!.event_logging.v4.DataComplexTypeB\010\272H\005" +
      "\222\001\002\010\000R\004dataB\342\001\n\034uk.gov.gchq.event_loggin" +
      "g.v4B\036NetworkOutcomeComplexTypeProtoP\001ZE" +
      "github.com/gchq/event-logging-schema/eve" +
      "nt_logging/v4;event_loggingv4\242\002\003EXX\252\002\017Ev" +
      "entLogging.V4\312\002\017EventLogging\\V4\342\002\033EventL" +
      "ogging\\V4\\GPBMetadata\352\002\020EventLogging::V4" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          uk.gov.gchq.event_logging.v4.DataComplexTypeProto.getDescriptor(),
          uk.gov.gchq.event_logging.v4.MultiObjectComplexTypeProto.getDescriptor(),
          uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeProto.getDescriptor(),
          uk.gov.gchq.event_logging.v4.OutcomeComplexTypeProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_event_logging_v4_NetworkOutcomeComplexType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_logging_v4_NetworkOutcomeComplexType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_event_logging_v4_NetworkOutcomeComplexType_descriptor,
        new java.lang.String[] { "Source", "Destination", "ProcessName", "Payload", "Rule", "Outcome", "Data", });
    descriptor.resolveAllFeaturesImmutable();
    uk.gov.gchq.event_logging.v4.DataComplexTypeProto.getDescriptor();
    uk.gov.gchq.event_logging.v4.MultiObjectComplexTypeProto.getDescriptor();
    uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeProto.getDescriptor();
    uk.gov.gchq.event_logging.v4.OutcomeComplexTypeProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
