// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/network_protocol_simple_type.proto

// Protobuf Java Version: 4.26.1
package uk.gov.gchq.event_logging.v4;

/**
 * <pre>
 * The different types of network protocol.
 * </pre>
 *
 * Protobuf enum {@code event_logging.v4.NetworkProtocolSimpleType}
 */
public enum NetworkProtocolSimpleType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default
   * </pre>
   *
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_UNSPECIFIED = 0;</code>
   */
  NETWORK_PROTOCOL_SIMPLE_TYPE_UNSPECIFIED(0),
  /**
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_TCP = 1;</code>
   */
  NETWORK_PROTOCOL_SIMPLE_TYPE_TCP(1),
  /**
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_UDP = 2;</code>
   */
  NETWORK_PROTOCOL_SIMPLE_TYPE_UDP(2),
  /**
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_ICMP = 3;</code>
   */
  NETWORK_PROTOCOL_SIMPLE_TYPE_ICMP(3),
  /**
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_IGMP = 4;</code>
   */
  NETWORK_PROTOCOL_SIMPLE_TYPE_IGMP(4),
  /**
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_OTHER = 5;</code>
   */
  NETWORK_PROTOCOL_SIMPLE_TYPE_OTHER(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      NetworkProtocolSimpleType.class.getName());
  }
  /**
   * <pre>
   * Default
   * </pre>
   *
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int NETWORK_PROTOCOL_SIMPLE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_TCP = 1;</code>
   */
  public static final int NETWORK_PROTOCOL_SIMPLE_TYPE_TCP_VALUE = 1;
  /**
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_UDP = 2;</code>
   */
  public static final int NETWORK_PROTOCOL_SIMPLE_TYPE_UDP_VALUE = 2;
  /**
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_ICMP = 3;</code>
   */
  public static final int NETWORK_PROTOCOL_SIMPLE_TYPE_ICMP_VALUE = 3;
  /**
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_IGMP = 4;</code>
   */
  public static final int NETWORK_PROTOCOL_SIMPLE_TYPE_IGMP_VALUE = 4;
  /**
   * <code>NETWORK_PROTOCOL_SIMPLE_TYPE_OTHER = 5;</code>
   */
  public static final int NETWORK_PROTOCOL_SIMPLE_TYPE_OTHER_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static NetworkProtocolSimpleType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static NetworkProtocolSimpleType forNumber(int value) {
    switch (value) {
      case 0: return NETWORK_PROTOCOL_SIMPLE_TYPE_UNSPECIFIED;
      case 1: return NETWORK_PROTOCOL_SIMPLE_TYPE_TCP;
      case 2: return NETWORK_PROTOCOL_SIMPLE_TYPE_UDP;
      case 3: return NETWORK_PROTOCOL_SIMPLE_TYPE_ICMP;
      case 4: return NETWORK_PROTOCOL_SIMPLE_TYPE_IGMP;
      case 5: return NETWORK_PROTOCOL_SIMPLE_TYPE_OTHER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<NetworkProtocolSimpleType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      NetworkProtocolSimpleType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<NetworkProtocolSimpleType>() {
          public NetworkProtocolSimpleType findValueByNumber(int number) {
            return NetworkProtocolSimpleType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return uk.gov.gchq.event_logging.v4.NetworkProtocolSimpleTypeProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final NetworkProtocolSimpleType[] VALUES = values();

  public static NetworkProtocolSimpleType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private NetworkProtocolSimpleType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:event_logging.v4.NetworkProtocolSimpleType)
}

