// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/network_complex_type.proto

// Protobuf Java Version: 4.26.1
package uk.gov.gchq.event_logging.v4;

/**
 * <pre>
 * A type to describe part of a computer network or some activity on a network.
 * </pre>
 *
 * Protobuf type {@code event_logging.v4.NetworkComplexType}
 */
public final class NetworkComplexType extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:event_logging.v4.NetworkComplexType)
    NetworkComplexTypeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      NetworkComplexType.class.getName());
  }
  // Use NetworkComplexType.newBuilder() to construct.
  private NetworkComplexType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private NetworkComplexType() {
    processName_ = "";
    rule_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return uk.gov.gchq.event_logging.v4.NetworkComplexTypeProto.internal_static_event_logging_v4_NetworkComplexType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return uk.gov.gchq.event_logging.v4.NetworkComplexTypeProto.internal_static_event_logging_v4_NetworkComplexType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            uk.gov.gchq.event_logging.v4.NetworkComplexType.class, uk.gov.gchq.event_logging.v4.NetworkComplexType.Builder.class);
  }

  private int bitField0_;
  public static final int SOURCE_FIELD_NUMBER = 1;
  private uk.gov.gchq.event_logging.v4.NetworkLocationComplexType source_;
  /**
   * <pre>
   * The source device that is attempting the network action.
   * </pre>
   *
   * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
   * @return Whether the source field is set.
   */
  @java.lang.Override
  public boolean hasSource() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The source device that is attempting the network action.
   * </pre>
   *
   * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
   * @return The source.
   */
  @java.lang.Override
  public uk.gov.gchq.event_logging.v4.NetworkLocationComplexType getSource() {
    return source_ == null ? uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.getDefaultInstance() : source_;
  }
  /**
   * <pre>
   * The source device that is attempting the network action.
   * </pre>
   *
   * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeOrBuilder getSourceOrBuilder() {
    return source_ == null ? uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.getDefaultInstance() : source_;
  }

  public static final int DESTINATION_FIELD_NUMBER = 2;
  private uk.gov.gchq.event_logging.v4.NetworkLocationComplexType destination_;
  /**
   * <pre>
   * The destination device for the network action.
   * </pre>
   *
   * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
   * @return Whether the destination field is set.
   */
  @java.lang.Override
  public boolean hasDestination() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The destination device for the network action.
   * </pre>
   *
   * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
   * @return The destination.
   */
  @java.lang.Override
  public uk.gov.gchq.event_logging.v4.NetworkLocationComplexType getDestination() {
    return destination_ == null ? uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.getDefaultInstance() : destination_;
  }
  /**
   * <pre>
   * The destination device for the network action.
   * </pre>
   *
   * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
   */
  @java.lang.Override
  public uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeOrBuilder getDestinationOrBuilder() {
    return destination_ == null ? uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.getDefaultInstance() : destination_;
  }

  public static final int PROCESS_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object processName_ = "";
  /**
   * <pre>
   * The name of the process responsible for the network action.
   * </pre>
   *
   * <code>string process_name = 3 [json_name = "processName"];</code>
   * @return The processName.
   */
  @java.lang.Override
  public java.lang.String getProcessName() {
    java.lang.Object ref = processName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name of the process responsible for the network action.
   * </pre>
   *
   * <code>string process_name = 3 [json_name = "processName"];</code>
   * @return The bytes for processName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProcessNameBytes() {
    java.lang.Object ref = processName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      processName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 4;
  private uk.gov.gchq.event_logging.v4.MultiObjectComplexType payload_;
  /**
   * <pre>
   * If the network action is related to message transfer from one place to another then this element describes the message.
   * </pre>
   *
   * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
   * @return Whether the payload field is set.
   */
  @java.lang.Override
  public boolean hasPayload() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * If the network action is related to message transfer from one place to another then this element describes the message.
   * </pre>
   *
   * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
   * @return The payload.
   */
  @java.lang.Override
  public uk.gov.gchq.event_logging.v4.MultiObjectComplexType getPayload() {
    return payload_ == null ? uk.gov.gchq.event_logging.v4.MultiObjectComplexType.getDefaultInstance() : payload_;
  }
  /**
   * <pre>
   * If the network action is related to message transfer from one place to another then this element describes the message.
   * </pre>
   *
   * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
   */
  @java.lang.Override
  public uk.gov.gchq.event_logging.v4.MultiObjectComplexTypeOrBuilder getPayloadOrBuilder() {
    return payload_ == null ? uk.gov.gchq.event_logging.v4.MultiObjectComplexType.getDefaultInstance() : payload_;
  }

  public static final int RULE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rule_ = "";
  /**
   * <pre>
   * The network boundary filter rule that was fired to generate this event.
   * </pre>
   *
   * <code>string rule = 5 [json_name = "rule"];</code>
   * @return The rule.
   */
  @java.lang.Override
  public java.lang.String getRule() {
    java.lang.Object ref = rule_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rule_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The network boundary filter rule that was fired to generate this event.
   * </pre>
   *
   * <code>string rule = 5 [json_name = "rule"];</code>
   * @return The bytes for rule.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRuleBytes() {
    java.lang.Object ref = rule_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rule_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getSource());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getDestination());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(processName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, processName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getPayload());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rule_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, rule_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSource());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDestination());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(processName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, processName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getPayload());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(rule_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, rule_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof uk.gov.gchq.event_logging.v4.NetworkComplexType)) {
      return super.equals(obj);
    }
    uk.gov.gchq.event_logging.v4.NetworkComplexType other = (uk.gov.gchq.event_logging.v4.NetworkComplexType) obj;

    if (hasSource() != other.hasSource()) return false;
    if (hasSource()) {
      if (!getSource()
          .equals(other.getSource())) return false;
    }
    if (hasDestination() != other.hasDestination()) return false;
    if (hasDestination()) {
      if (!getDestination()
          .equals(other.getDestination())) return false;
    }
    if (!getProcessName()
        .equals(other.getProcessName())) return false;
    if (hasPayload() != other.hasPayload()) return false;
    if (hasPayload()) {
      if (!getPayload()
          .equals(other.getPayload())) return false;
    }
    if (!getRule()
        .equals(other.getRule())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSource()) {
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
    }
    if (hasDestination()) {
      hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + getDestination().hashCode();
    }
    hash = (37 * hash) + PROCESS_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getProcessName().hashCode();
    if (hasPayload()) {
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
    }
    hash = (37 * hash) + RULE_FIELD_NUMBER;
    hash = (53 * hash) + getRule().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static uk.gov.gchq.event_logging.v4.NetworkComplexType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(uk.gov.gchq.event_logging.v4.NetworkComplexType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A type to describe part of a computer network or some activity on a network.
   * </pre>
   *
   * Protobuf type {@code event_logging.v4.NetworkComplexType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:event_logging.v4.NetworkComplexType)
      uk.gov.gchq.event_logging.v4.NetworkComplexTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.gov.gchq.event_logging.v4.NetworkComplexTypeProto.internal_static_event_logging_v4_NetworkComplexType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.gov.gchq.event_logging.v4.NetworkComplexTypeProto.internal_static_event_logging_v4_NetworkComplexType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.gov.gchq.event_logging.v4.NetworkComplexType.class, uk.gov.gchq.event_logging.v4.NetworkComplexType.Builder.class);
    }

    // Construct using uk.gov.gchq.event_logging.v4.NetworkComplexType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getSourceFieldBuilder();
        getDestinationFieldBuilder();
        getPayloadFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      source_ = null;
      if (sourceBuilder_ != null) {
        sourceBuilder_.dispose();
        sourceBuilder_ = null;
      }
      destination_ = null;
      if (destinationBuilder_ != null) {
        destinationBuilder_.dispose();
        destinationBuilder_ = null;
      }
      processName_ = "";
      payload_ = null;
      if (payloadBuilder_ != null) {
        payloadBuilder_.dispose();
        payloadBuilder_ = null;
      }
      rule_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return uk.gov.gchq.event_logging.v4.NetworkComplexTypeProto.internal_static_event_logging_v4_NetworkComplexType_descriptor;
    }

    @java.lang.Override
    public uk.gov.gchq.event_logging.v4.NetworkComplexType getDefaultInstanceForType() {
      return uk.gov.gchq.event_logging.v4.NetworkComplexType.getDefaultInstance();
    }

    @java.lang.Override
    public uk.gov.gchq.event_logging.v4.NetworkComplexType build() {
      uk.gov.gchq.event_logging.v4.NetworkComplexType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public uk.gov.gchq.event_logging.v4.NetworkComplexType buildPartial() {
      uk.gov.gchq.event_logging.v4.NetworkComplexType result = new uk.gov.gchq.event_logging.v4.NetworkComplexType(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(uk.gov.gchq.event_logging.v4.NetworkComplexType result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.source_ = sourceBuilder_ == null
            ? source_
            : sourceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.destination_ = destinationBuilder_ == null
            ? destination_
            : destinationBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.processName_ = processName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.payload_ = payloadBuilder_ == null
            ? payload_
            : payloadBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.rule_ = rule_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof uk.gov.gchq.event_logging.v4.NetworkComplexType) {
        return mergeFrom((uk.gov.gchq.event_logging.v4.NetworkComplexType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(uk.gov.gchq.event_logging.v4.NetworkComplexType other) {
      if (other == uk.gov.gchq.event_logging.v4.NetworkComplexType.getDefaultInstance()) return this;
      if (other.hasSource()) {
        mergeSource(other.getSource());
      }
      if (other.hasDestination()) {
        mergeDestination(other.getDestination());
      }
      if (!other.getProcessName().isEmpty()) {
        processName_ = other.processName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasPayload()) {
        mergePayload(other.getPayload());
      }
      if (!other.getRule().isEmpty()) {
        rule_ = other.rule_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getSourceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getDestinationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              processName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getPayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              rule_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private uk.gov.gchq.event_logging.v4.NetworkLocationComplexType source_;
    private com.google.protobuf.SingleFieldBuilder<
        uk.gov.gchq.event_logging.v4.NetworkLocationComplexType, uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.Builder, uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeOrBuilder> sourceBuilder_;
    /**
     * <pre>
     * The source device that is attempting the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
     * @return Whether the source field is set.
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The source device that is attempting the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
     * @return The source.
     */
    public uk.gov.gchq.event_logging.v4.NetworkLocationComplexType getSource() {
      if (sourceBuilder_ == null) {
        return source_ == null ? uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.getDefaultInstance() : source_;
      } else {
        return sourceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The source device that is attempting the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
     */
    public Builder setSource(uk.gov.gchq.event_logging.v4.NetworkLocationComplexType value) {
      if (sourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        source_ = value;
      } else {
        sourceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The source device that is attempting the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
     */
    public Builder setSource(
        uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.Builder builderForValue) {
      if (sourceBuilder_ == null) {
        source_ = builderForValue.build();
      } else {
        sourceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The source device that is attempting the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
     */
    public Builder mergeSource(uk.gov.gchq.event_logging.v4.NetworkLocationComplexType value) {
      if (sourceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          source_ != null &&
          source_ != uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.getDefaultInstance()) {
          getSourceBuilder().mergeFrom(value);
        } else {
          source_ = value;
        }
      } else {
        sourceBuilder_.mergeFrom(value);
      }
      if (source_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The source device that is attempting the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearSource() {
      bitField0_ = (bitField0_ & ~0x00000001);
      source_ = null;
      if (sourceBuilder_ != null) {
        sourceBuilder_.dispose();
        sourceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The source device that is attempting the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
     */
    public uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.Builder getSourceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getSourceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The source device that is attempting the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
     */
    public uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeOrBuilder getSourceOrBuilder() {
      if (sourceBuilder_ != null) {
        return sourceBuilder_.getMessageOrBuilder();
      } else {
        return source_ == null ?
            uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.getDefaultInstance() : source_;
      }
    }
    /**
     * <pre>
     * The source device that is attempting the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType source = 1 [json_name = "source", (.buf.validate.field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        uk.gov.gchq.event_logging.v4.NetworkLocationComplexType, uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.Builder, uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeOrBuilder> 
        getSourceFieldBuilder() {
      if (sourceBuilder_ == null) {
        sourceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            uk.gov.gchq.event_logging.v4.NetworkLocationComplexType, uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.Builder, uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeOrBuilder>(
                getSource(),
                getParentForChildren(),
                isClean());
        source_ = null;
      }
      return sourceBuilder_;
    }

    private uk.gov.gchq.event_logging.v4.NetworkLocationComplexType destination_;
    private com.google.protobuf.SingleFieldBuilder<
        uk.gov.gchq.event_logging.v4.NetworkLocationComplexType, uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.Builder, uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeOrBuilder> destinationBuilder_;
    /**
     * <pre>
     * The destination device for the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
     * @return Whether the destination field is set.
     */
    public boolean hasDestination() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The destination device for the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
     * @return The destination.
     */
    public uk.gov.gchq.event_logging.v4.NetworkLocationComplexType getDestination() {
      if (destinationBuilder_ == null) {
        return destination_ == null ? uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.getDefaultInstance() : destination_;
      } else {
        return destinationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The destination device for the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
     */
    public Builder setDestination(uk.gov.gchq.event_logging.v4.NetworkLocationComplexType value) {
      if (destinationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        destination_ = value;
      } else {
        destinationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The destination device for the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
     */
    public Builder setDestination(
        uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.Builder builderForValue) {
      if (destinationBuilder_ == null) {
        destination_ = builderForValue.build();
      } else {
        destinationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The destination device for the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
     */
    public Builder mergeDestination(uk.gov.gchq.event_logging.v4.NetworkLocationComplexType value) {
      if (destinationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          destination_ != null &&
          destination_ != uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.getDefaultInstance()) {
          getDestinationBuilder().mergeFrom(value);
        } else {
          destination_ = value;
        }
      } else {
        destinationBuilder_.mergeFrom(value);
      }
      if (destination_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The destination device for the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
     */
    public Builder clearDestination() {
      bitField0_ = (bitField0_ & ~0x00000002);
      destination_ = null;
      if (destinationBuilder_ != null) {
        destinationBuilder_.dispose();
        destinationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The destination device for the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
     */
    public uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.Builder getDestinationBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getDestinationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The destination device for the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
     */
    public uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeOrBuilder getDestinationOrBuilder() {
      if (destinationBuilder_ != null) {
        return destinationBuilder_.getMessageOrBuilder();
      } else {
        return destination_ == null ?
            uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.getDefaultInstance() : destination_;
      }
    }
    /**
     * <pre>
     * The destination device for the network action.
     * </pre>
     *
     * <code>.event_logging.v4.NetworkLocationComplexType destination = 2 [json_name = "destination"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        uk.gov.gchq.event_logging.v4.NetworkLocationComplexType, uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.Builder, uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeOrBuilder> 
        getDestinationFieldBuilder() {
      if (destinationBuilder_ == null) {
        destinationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            uk.gov.gchq.event_logging.v4.NetworkLocationComplexType, uk.gov.gchq.event_logging.v4.NetworkLocationComplexType.Builder, uk.gov.gchq.event_logging.v4.NetworkLocationComplexTypeOrBuilder>(
                getDestination(),
                getParentForChildren(),
                isClean());
        destination_ = null;
      }
      return destinationBuilder_;
    }

    private java.lang.Object processName_ = "";
    /**
     * <pre>
     * The name of the process responsible for the network action.
     * </pre>
     *
     * <code>string process_name = 3 [json_name = "processName"];</code>
     * @return The processName.
     */
    public java.lang.String getProcessName() {
      java.lang.Object ref = processName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The name of the process responsible for the network action.
     * </pre>
     *
     * <code>string process_name = 3 [json_name = "processName"];</code>
     * @return The bytes for processName.
     */
    public com.google.protobuf.ByteString
        getProcessNameBytes() {
      java.lang.Object ref = processName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name of the process responsible for the network action.
     * </pre>
     *
     * <code>string process_name = 3 [json_name = "processName"];</code>
     * @param value The processName to set.
     * @return This builder for chaining.
     */
    public Builder setProcessName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      processName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the process responsible for the network action.
     * </pre>
     *
     * <code>string process_name = 3 [json_name = "processName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessName() {
      processName_ = getDefaultInstance().getProcessName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the process responsible for the network action.
     * </pre>
     *
     * <code>string process_name = 3 [json_name = "processName"];</code>
     * @param value The bytes for processName to set.
     * @return This builder for chaining.
     */
    public Builder setProcessNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      processName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private uk.gov.gchq.event_logging.v4.MultiObjectComplexType payload_;
    private com.google.protobuf.SingleFieldBuilder<
        uk.gov.gchq.event_logging.v4.MultiObjectComplexType, uk.gov.gchq.event_logging.v4.MultiObjectComplexType.Builder, uk.gov.gchq.event_logging.v4.MultiObjectComplexTypeOrBuilder> payloadBuilder_;
    /**
     * <pre>
     * If the network action is related to message transfer from one place to another then this element describes the message.
     * </pre>
     *
     * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
     * @return Whether the payload field is set.
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * If the network action is related to message transfer from one place to another then this element describes the message.
     * </pre>
     *
     * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
     * @return The payload.
     */
    public uk.gov.gchq.event_logging.v4.MultiObjectComplexType getPayload() {
      if (payloadBuilder_ == null) {
        return payload_ == null ? uk.gov.gchq.event_logging.v4.MultiObjectComplexType.getDefaultInstance() : payload_;
      } else {
        return payloadBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * If the network action is related to message transfer from one place to another then this element describes the message.
     * </pre>
     *
     * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
     */
    public Builder setPayload(uk.gov.gchq.event_logging.v4.MultiObjectComplexType value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
      } else {
        payloadBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If the network action is related to message transfer from one place to another then this element describes the message.
     * </pre>
     *
     * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
     */
    public Builder setPayload(
        uk.gov.gchq.event_logging.v4.MultiObjectComplexType.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        payload_ = builderForValue.build();
      } else {
        payloadBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If the network action is related to message transfer from one place to another then this element describes the message.
     * </pre>
     *
     * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
     */
    public Builder mergePayload(uk.gov.gchq.event_logging.v4.MultiObjectComplexType value) {
      if (payloadBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          payload_ != null &&
          payload_ != uk.gov.gchq.event_logging.v4.MultiObjectComplexType.getDefaultInstance()) {
          getPayloadBuilder().mergeFrom(value);
        } else {
          payload_ = value;
        }
      } else {
        payloadBuilder_.mergeFrom(value);
      }
      if (payload_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * If the network action is related to message transfer from one place to another then this element describes the message.
     * </pre>
     *
     * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
     */
    public Builder clearPayload() {
      bitField0_ = (bitField0_ & ~0x00000008);
      payload_ = null;
      if (payloadBuilder_ != null) {
        payloadBuilder_.dispose();
        payloadBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If the network action is related to message transfer from one place to another then this element describes the message.
     * </pre>
     *
     * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
     */
    public uk.gov.gchq.event_logging.v4.MultiObjectComplexType.Builder getPayloadBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getPayloadFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * If the network action is related to message transfer from one place to another then this element describes the message.
     * </pre>
     *
     * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
     */
    public uk.gov.gchq.event_logging.v4.MultiObjectComplexTypeOrBuilder getPayloadOrBuilder() {
      if (payloadBuilder_ != null) {
        return payloadBuilder_.getMessageOrBuilder();
      } else {
        return payload_ == null ?
            uk.gov.gchq.event_logging.v4.MultiObjectComplexType.getDefaultInstance() : payload_;
      }
    }
    /**
     * <pre>
     * If the network action is related to message transfer from one place to another then this element describes the message.
     * </pre>
     *
     * <code>.event_logging.v4.MultiObjectComplexType payload = 4 [json_name = "payload"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        uk.gov.gchq.event_logging.v4.MultiObjectComplexType, uk.gov.gchq.event_logging.v4.MultiObjectComplexType.Builder, uk.gov.gchq.event_logging.v4.MultiObjectComplexTypeOrBuilder> 
        getPayloadFieldBuilder() {
      if (payloadBuilder_ == null) {
        payloadBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            uk.gov.gchq.event_logging.v4.MultiObjectComplexType, uk.gov.gchq.event_logging.v4.MultiObjectComplexType.Builder, uk.gov.gchq.event_logging.v4.MultiObjectComplexTypeOrBuilder>(
                getPayload(),
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      return payloadBuilder_;
    }

    private java.lang.Object rule_ = "";
    /**
     * <pre>
     * The network boundary filter rule that was fired to generate this event.
     * </pre>
     *
     * <code>string rule = 5 [json_name = "rule"];</code>
     * @return The rule.
     */
    public java.lang.String getRule() {
      java.lang.Object ref = rule_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rule_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The network boundary filter rule that was fired to generate this event.
     * </pre>
     *
     * <code>string rule = 5 [json_name = "rule"];</code>
     * @return The bytes for rule.
     */
    public com.google.protobuf.ByteString
        getRuleBytes() {
      java.lang.Object ref = rule_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rule_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The network boundary filter rule that was fired to generate this event.
     * </pre>
     *
     * <code>string rule = 5 [json_name = "rule"];</code>
     * @param value The rule to set.
     * @return This builder for chaining.
     */
    public Builder setRule(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rule_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The network boundary filter rule that was fired to generate this event.
     * </pre>
     *
     * <code>string rule = 5 [json_name = "rule"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRule() {
      rule_ = getDefaultInstance().getRule();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The network boundary filter rule that was fired to generate this event.
     * </pre>
     *
     * <code>string rule = 5 [json_name = "rule"];</code>
     * @param value The bytes for rule to set.
     * @return This builder for chaining.
     */
    public Builder setRuleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rule_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:event_logging.v4.NetworkComplexType)
  }

  // @@protoc_insertion_point(class_scope:event_logging.v4.NetworkComplexType)
  private static final uk.gov.gchq.event_logging.v4.NetworkComplexType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new uk.gov.gchq.event_logging.v4.NetworkComplexType();
  }

  public static uk.gov.gchq.event_logging.v4.NetworkComplexType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetworkComplexType>
      PARSER = new com.google.protobuf.AbstractParser<NetworkComplexType>() {
    @java.lang.Override
    public NetworkComplexType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NetworkComplexType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetworkComplexType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public uk.gov.gchq.event_logging.v4.NetworkComplexType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

