// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/logic_complex_type.proto

// Protobuf Java Version: 4.26.1
package uk.gov.gchq.event_logging.v4;

public interface NotComplexTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event_logging.v4.NotComplexType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .event_logging.v4.NotComplexType.ChoiceWrapperNotComplexType choice_wrapper = 1 [json_name = "choiceWrapper", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<uk.gov.gchq.event_logging.v4.NotComplexType.ChoiceWrapperNotComplexType> 
      getChoiceWrapperList();
  /**
   * <code>repeated .event_logging.v4.NotComplexType.ChoiceWrapperNotComplexType choice_wrapper = 1 [json_name = "choiceWrapper", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.NotComplexType.ChoiceWrapperNotComplexType getChoiceWrapper(int index);
  /**
   * <code>repeated .event_logging.v4.NotComplexType.ChoiceWrapperNotComplexType choice_wrapper = 1 [json_name = "choiceWrapper", (.buf.validate.field) = { ... }</code>
   */
  int getChoiceWrapperCount();
  /**
   * <code>repeated .event_logging.v4.NotComplexType.ChoiceWrapperNotComplexType choice_wrapper = 1 [json_name = "choiceWrapper", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<? extends uk.gov.gchq.event_logging.v4.NotComplexType.ChoiceWrapperNotComplexTypeOrBuilder> 
      getChoiceWrapperOrBuilderList();
  /**
   * <code>repeated .event_logging.v4.NotComplexType.ChoiceWrapperNotComplexType choice_wrapper = 1 [json_name = "choiceWrapper", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.NotComplexType.ChoiceWrapperNotComplexTypeOrBuilder getChoiceWrapperOrBuilder(
      int index);
}
