// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/resource_complex_type.proto

// Protobuf Java Version: 4.26.1
package uk.gov.gchq.event_logging.v4;

public interface ResourceComplexTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event_logging.v4.ResourceComplexType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * This element can be used to supply any metadata relating to an object as long as it conforms to an allowed format/specification (defined outside this XML Schema). This can be used for adding metadata to the event after receipt.
   * </pre>
   *
   * <code>repeated .event_logging.v4.AnyContentComplexType meta = 1 [json_name = "meta", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<uk.gov.gchq.event_logging.v4.AnyContentComplexType> 
      getMetaList();
  /**
   * <pre>
   * This element can be used to supply any metadata relating to an object as long as it conforms to an allowed format/specification (defined outside this XML Schema). This can be used for adding metadata to the event after receipt.
   * </pre>
   *
   * <code>repeated .event_logging.v4.AnyContentComplexType meta = 1 [json_name = "meta", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.AnyContentComplexType getMeta(int index);
  /**
   * <pre>
   * This element can be used to supply any metadata relating to an object as long as it conforms to an allowed format/specification (defined outside this XML Schema). This can be used for adding metadata to the event after receipt.
   * </pre>
   *
   * <code>repeated .event_logging.v4.AnyContentComplexType meta = 1 [json_name = "meta", (.buf.validate.field) = { ... }</code>
   */
  int getMetaCount();
  /**
   * <pre>
   * This element can be used to supply any metadata relating to an object as long as it conforms to an allowed format/specification (defined outside this XML Schema). This can be used for adding metadata to the event after receipt.
   * </pre>
   *
   * <code>repeated .event_logging.v4.AnyContentComplexType meta = 1 [json_name = "meta", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<? extends uk.gov.gchq.event_logging.v4.AnyContentComplexTypeOrBuilder> 
      getMetaOrBuilderList();
  /**
   * <pre>
   * This element can be used to supply any metadata relating to an object as long as it conforms to an allowed format/specification (defined outside this XML Schema). This can be used for adding metadata to the event after receipt.
   * </pre>
   *
   * <code>repeated .event_logging.v4.AnyContentComplexType meta = 1 [json_name = "meta", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.AnyContentComplexTypeOrBuilder getMetaOrBuilder(
      int index);

  /**
   * <pre>
   * The type of the object in question and specific to the object type from the list above, e.g. a 'Resource' object may have a type such as 'image' or 'script'.
   * </pre>
   *
   * <code>string type = 2 [json_name = "type"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * The type of the object in question and specific to the object type from the list above, e.g. a 'Resource' object may have a type such as 'image' or 'script'.
   * </pre>
   *
   * <code>string type = 2 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * An identifier for the object, e.g a document ID in a document management system. This ID is likely to be specific to the system that generated the event.
   * </pre>
   *
   * <code>string id = 3 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * An identifier for the object, e.g a document ID in a document management system. This ID is likely to be specific to the system that generated the event.
   * </pre>
   *
   * <code>string id = 3 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The name of the object, e.g. a filename.
   * </pre>
   *
   * <code>string name = 4 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the object, e.g. a filename.
   * </pre>
   *
   * <code>string name = 4 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Human readable description of what the object is.
   * </pre>
   *
   * <code>string description = 5 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Human readable description of what the object is.
   * </pre>
   *
   * <code>string description = 5 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * Any classification, protective marking or restrictions placed on the object, e.g. for commercially sensitive reports or user health records.
   * </pre>
   *
   * <code>.event_logging.v4.ClassificationComplexType classification = 6 [json_name = "classification"];</code>
   * @return Whether the classification field is set.
   */
  boolean hasClassification();
  /**
   * <pre>
   * Any classification, protective marking or restrictions placed on the object, e.g. for commercially sensitive reports or user health records.
   * </pre>
   *
   * <code>.event_logging.v4.ClassificationComplexType classification = 6 [json_name = "classification"];</code>
   * @return The classification.
   */
  uk.gov.gchq.event_logging.v4.ClassificationComplexType getClassification();
  /**
   * <pre>
   * Any classification, protective marking or restrictions placed on the object, e.g. for commercially sensitive reports or user health records.
   * </pre>
   *
   * <code>.event_logging.v4.ClassificationComplexType classification = 6 [json_name = "classification"];</code>
   */
  uk.gov.gchq.event_logging.v4.ClassificationComplexTypeOrBuilder getClassificationOrBuilder();

  /**
   * <pre>
   * Any state information about the object, e.g. 'Archived'.
   * </pre>
   *
   * <code>string state = 7 [json_name = "state"];</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <pre>
   * Any state information about the object, e.g. 'Archived'.
   * </pre>
   *
   * <code>string state = 7 [json_name = "state"];</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <pre>
   * Any groups associated with the object, e.g. group membership of a user account.
   * </pre>
   *
   * <code>.event_logging.v4.GroupsComplexType groups = 8 [json_name = "groups"];</code>
   * @return Whether the groups field is set.
   */
  boolean hasGroups();
  /**
   * <pre>
   * Any groups associated with the object, e.g. group membership of a user account.
   * </pre>
   *
   * <code>.event_logging.v4.GroupsComplexType groups = 8 [json_name = "groups"];</code>
   * @return The groups.
   */
  uk.gov.gchq.event_logging.v4.GroupsComplexType getGroups();
  /**
   * <pre>
   * Any groups associated with the object, e.g. group membership of a user account.
   * </pre>
   *
   * <code>.event_logging.v4.GroupsComplexType groups = 8 [json_name = "groups"];</code>
   */
  uk.gov.gchq.event_logging.v4.GroupsComplexTypeOrBuilder getGroupsOrBuilder();

  /**
   * <pre>
   * The collection of permissions associated with the object, e.g. write access being granted to a list of named users.
   * </pre>
   *
   * <code>.event_logging.v4.ResourceComplexType.PermissionsType permissions = 9 [json_name = "permissions"];</code>
   * @return Whether the permissions field is set.
   */
  boolean hasPermissions();
  /**
   * <pre>
   * The collection of permissions associated with the object, e.g. write access being granted to a list of named users.
   * </pre>
   *
   * <code>.event_logging.v4.ResourceComplexType.PermissionsType permissions = 9 [json_name = "permissions"];</code>
   * @return The permissions.
   */
  uk.gov.gchq.event_logging.v4.ResourceComplexType.PermissionsType getPermissions();
  /**
   * <pre>
   * The collection of permissions associated with the object, e.g. write access being granted to a list of named users.
   * </pre>
   *
   * <code>.event_logging.v4.ResourceComplexType.PermissionsType permissions = 9 [json_name = "permissions"];</code>
   */
  uk.gov.gchq.event_logging.v4.ResourceComplexType.PermissionsTypeOrBuilder getPermissionsOrBuilder();

  /**
   * <pre>
   * Metadata tags that can be used for additional object tagging or categorisation. Object tagging allows for the labelling (or filtering) of objects using words that label, categorise or group similar items, using a taxonomy defined outside this schema. For example, an email could be tagged with tags like 'internal', 'spam', 'external', 'rich-content', etc.
   * </pre>
   *
   * <code>.event_logging.v4.MetaDataTagsComplexType tags = 10 [json_name = "tags"];</code>
   * @return Whether the tags field is set.
   */
  boolean hasTags();
  /**
   * <pre>
   * Metadata tags that can be used for additional object tagging or categorisation. Object tagging allows for the labelling (or filtering) of objects using words that label, categorise or group similar items, using a taxonomy defined outside this schema. For example, an email could be tagged with tags like 'internal', 'spam', 'external', 'rich-content', etc.
   * </pre>
   *
   * <code>.event_logging.v4.MetaDataTagsComplexType tags = 10 [json_name = "tags"];</code>
   * @return The tags.
   */
  uk.gov.gchq.event_logging.v4.MetaDataTagsComplexType getTags();
  /**
   * <pre>
   * Metadata tags that can be used for additional object tagging or categorisation. Object tagging allows for the labelling (or filtering) of objects using words that label, categorise or group similar items, using a taxonomy defined outside this schema. For example, an email could be tagged with tags like 'internal', 'spam', 'external', 'rich-content', etc.
   * </pre>
   *
   * <code>.event_logging.v4.MetaDataTagsComplexType tags = 10 [json_name = "tags"];</code>
   */
  uk.gov.gchq.event_logging.v4.MetaDataTagsComplexTypeOrBuilder getTagsOrBuilder();

  /**
   * <pre>
   * The title of the resource or of the object the resource presents.
   * </pre>
   *
   * <code>string title = 11 [json_name = "title"];</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * The title of the resource or of the object the resource presents.
   * </pre>
   *
   * <code>string title = 11 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * The URL of the resource the event relates to
   * </pre>
   *
   * <code>string url = 12 [json_name = "url"];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * The URL of the resource the event relates to
   * </pre>
   *
   * <code>string url = 12 [json_name = "url"];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * The URL of the resource that referred to the URL of this event
   * </pre>
   *
   * <code>string referrer = 13 [json_name = "referrer"];</code>
   * @return The referrer.
   */
  java.lang.String getReferrer();
  /**
   * <pre>
   * The URL of the resource that referred to the URL of this event
   * </pre>
   *
   * <code>string referrer = 13 [json_name = "referrer"];</code>
   * @return The bytes for referrer.
   */
  com.google.protobuf.ByteString
      getReferrerBytes();

  /**
   * <pre>
   * The session identifier or token used to identify a session or series of related message exchanges.
   * </pre>
   *
   * <code>string session_id = 14 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * The session identifier or token used to identify a session or series of related message exchanges.
   * </pre>
   *
   * <code>string session_id = 14 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * The HTTP method, e.g. GET, POST, DELETE, PUT etc
   * </pre>
   *
   * <code>string http_method = 15 [json_name = "httpMethod"];</code>
   * @return The httpMethod.
   */
  java.lang.String getHttpMethod();
  /**
   * <pre>
   * The HTTP method, e.g. GET, POST, DELETE, PUT etc
   * </pre>
   *
   * <code>string http_method = 15 [json_name = "httpMethod"];</code>
   * @return The bytes for httpMethod.
   */
  com.google.protobuf.ByteString
      getHttpMethodBytes();

  /**
   * <pre>
   * The HTTP version, e.g. 1.1
   * </pre>
   *
   * <code>string http_version = 16 [json_name = "httpVersion"];</code>
   * @return The httpVersion.
   */
  java.lang.String getHttpVersion();
  /**
   * <pre>
   * The HTTP version, e.g. 1.1
   * </pre>
   *
   * <code>string http_version = 16 [json_name = "httpVersion"];</code>
   * @return The bytes for httpVersion.
   */
  com.google.protobuf.ByteString
      getHttpVersionBytes();

  /**
   * <pre>
   * This is a string provided by the initiating software agent used to identify itself, its application type, operating system, software vendor or software version. This string typically appears as a field in a request message with a field header name of 'User-Agent'.
   * </pre>
   *
   * <code>string user_agent = 17 [json_name = "userAgent"];</code>
   * @return The userAgent.
   */
  java.lang.String getUserAgent();
  /**
   * <pre>
   * This is a string provided by the initiating software agent used to identify itself, its application type, operating system, software vendor or software version. This string typically appears as a field in a request message with a field header name of 'User-Agent'.
   * </pre>
   *
   * <code>string user_agent = 17 [json_name = "userAgent"];</code>
   * @return The bytes for userAgent.
   */
  com.google.protobuf.ByteString
      getUserAgentBytes();

  /**
   * <pre>
   * The size in bytes received, including the request and HTTP headers.
   * </pre>
   *
   * <code>uint32 inbound_size = 18 [json_name = "inboundSize", (.buf.validate.field) = { ... }</code>
   * @return The inboundSize.
   */
  int getInboundSize();

  /**
   * <pre>
   * The size in bytes of the incoming data, EXCLUDING HTTP headers.
   * </pre>
   *
   * <code>uint32 inbound_content_size = 19 [json_name = "inboundContentSize", (.buf.validate.field) = { ... }</code>
   * @return The inboundContentSize.
   */
  int getInboundContentSize();

  /**
   * <pre>
   * The HTTP request header.
   * </pre>
   *
   * <code>string inbound_header = 20 [json_name = "inboundHeader"];</code>
   * @return The inboundHeader.
   */
  java.lang.String getInboundHeader();
  /**
   * <pre>
   * The HTTP request header.
   * </pre>
   *
   * <code>string inbound_header = 20 [json_name = "inboundHeader"];</code>
   * @return The bytes for inboundHeader.
   */
  com.google.protobuf.ByteString
      getInboundHeaderBytes();

  /**
   * <pre>
   * The size in bytes of the outgoing data, including HTTP headers.
   * </pre>
   *
   * <code>uint32 outbound_size = 21 [json_name = "outboundSize", (.buf.validate.field) = { ... }</code>
   * @return The outboundSize.
   */
  int getOutboundSize();

  /**
   * <pre>
   * The size in bytes of the outgoing data, EXCLUDING HTTP headers.
   * </pre>
   *
   * <code>uint32 outbound_content_size = 22 [json_name = "outboundContentSize", (.buf.validate.field) = { ... }</code>
   * @return The outboundContentSize.
   */
  int getOutboundContentSize();

  /**
   * <pre>
   * The HTTP response header.
   * </pre>
   *
   * <code>string outbound_header = 23 [json_name = "outboundHeader"];</code>
   * @return The outboundHeader.
   */
  java.lang.String getOutboundHeader();
  /**
   * <pre>
   * The HTTP response header.
   * </pre>
   *
   * <code>string outbound_header = 23 [json_name = "outboundHeader"];</code>
   * @return The bytes for outboundHeader.
   */
  com.google.protobuf.ByteString
      getOutboundHeaderBytes();

  /**
   * <pre>
   * The number of microseconds the server took to handle the request.
   * </pre>
   *
   * <code>uint32 request_time = 24 [json_name = "requestTime", (.buf.validate.field) = { ... }</code>
   * @return The requestTime.
   */
  int getRequestTime();

  /**
   * <pre>
   * The connection status of the client connection.
   * </pre>
   *
   * <code>string connection_status = 25 [json_name = "connectionStatus"];</code>
   * @return The connectionStatus.
   */
  java.lang.String getConnectionStatus();
  /**
   * <pre>
   * The connection status of the client connection.
   * </pre>
   *
   * <code>string connection_status = 25 [json_name = "connectionStatus"];</code>
   * @return The bytes for connectionStatus.
   */
  com.google.protobuf.ByteString
      getConnectionStatusBytes();

  /**
   * <pre>
   * The status code of the original request.
   * </pre>
   *
   * <code>string initial_response_code = 26 [json_name = "initialResponseCode"];</code>
   * @return The initialResponseCode.
   */
  java.lang.String getInitialResponseCode();
  /**
   * <pre>
   * The status code of the original request.
   * </pre>
   *
   * <code>string initial_response_code = 26 [json_name = "initialResponseCode"];</code>
   * @return The bytes for initialResponseCode.
   */
  com.google.protobuf.ByteString
      getInitialResponseCodeBytes();

  /**
   * <pre>
   * The final status code of the request, after any internal redirections may have taken place.
   * </pre>
   *
   * <code>string response_code = 27 [json_name = "responseCode"];</code>
   * @return The responseCode.
   */
  java.lang.String getResponseCode();
  /**
   * <pre>
   * The final status code of the request, after any internal redirections may have taken place.
   * </pre>
   *
   * <code>string response_code = 27 [json_name = "responseCode"];</code>
   * @return The bytes for responseCode.
   */
  com.google.protobuf.ByteString
      getResponseCodeBytes();

  /**
   * <pre>
   * The Internet Media Type identifying the file format of the resource provided (format of request or response body). This string typically appears in the 'Content-Type' field of a Request or Response Header.
   * </pre>
   *
   * <code>string mime_type = 28 [json_name = "mimeType"];</code>
   * @return The mimeType.
   */
  java.lang.String getMimeType();
  /**
   * <pre>
   * The Internet Media Type identifying the file format of the resource provided (format of request or response body). This string typically appears in the 'Content-Type' field of a Request or Response Header.
   * </pre>
   *
   * <code>string mime_type = 28 [json_name = "mimeType"];</code>
   * @return The bytes for mimeType.
   */
  com.google.protobuf.ByteString
      getMimeTypeBytes();

  /**
   * <pre>
   * The category of a web page or resource where a categorisation engine is used, e.g. News, Search Engine, Social Media, etc.
   * </pre>
   *
   * <code>string category = 29 [json_name = "category"];</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <pre>
   * The category of a web page or resource where a categorisation engine is used, e.g. News, Search Engine, Social Media, etc.
   * </pre>
   *
   * <code>string category = 29 [json_name = "category"];</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <pre>
   * Any other event data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 30 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<uk.gov.gchq.event_logging.v4.DataComplexType> 
      getDataList();
  /**
   * <pre>
   * Any other event data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 30 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.DataComplexType getData(int index);
  /**
   * <pre>
   * Any other event data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 30 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  int getDataCount();
  /**
   * <pre>
   * Any other event data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 30 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<? extends uk.gov.gchq.event_logging.v4.DataComplexTypeOrBuilder> 
      getDataOrBuilderList();
  /**
   * <pre>
   * Any other event data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 30 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.DataComplexTypeOrBuilder getDataOrBuilder(
      int index);
}
