// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/term_complex_type.proto
// Protobuf Java Version: 4.26.1

package uk.gov.gchq.event_logging.v4;

public final class TermComplexTypeProto {
  private TermComplexTypeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      TermComplexTypeProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_logging_v4_TermComplexType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_event_logging_v4_TermComplexType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(event_logging/v4/term_complex_type.pro" +
      "to\022\020event_logging.v4\0321event_logging/v4/t" +
      "erm_condition_simple_type.proto\032\033buf/val" +
      "idate/validate.proto\"\234\001\n\017TermComplexType" +
      "\022\032\n\004name\030\001 \001(\tB\006\272H\003\310\001\001R\004name\022O\n\tconditio" +
      "n\030\002 \001(\0162).event_logging.v4.TermCondition" +
      "SimpleTypeB\006\272H\003\310\001\001R\tcondition\022\034\n\005value\030\003" +
      " \001(\tB\006\272H\003\310\001\001R\005valueB\330\001\n\034uk.gov.gchq.even" +
      "t_logging.v4B\024TermComplexTypeProtoP\001ZEgi" +
      "thub.com/gchq/event-logging-schema/event" +
      "_logging/v4;event_loggingv4\242\002\003EXX\252\002\017Even" +
      "tLogging.V4\312\002\017EventLogging\\V4\342\002\033EventLog" +
      "ging\\V4\\GPBMetadata\352\002\020EventLogging::V4b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          uk.gov.gchq.event_logging.v4.TermConditionSimpleTypeProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_event_logging_v4_TermComplexType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_logging_v4_TermComplexType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_event_logging_v4_TermComplexType_descriptor,
        new java.lang.String[] { "Name", "Condition", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    uk.gov.gchq.event_logging.v4.TermConditionSimpleTypeProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
