// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/update_complex_type.proto

// Protobuf Java Version: 4.26.1
package uk.gov.gchq.event_logging.v4;

public interface UpdateComplexTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event_logging.v4.UpdateComplexType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Describes the state of one or more object properties before it was changed.
   * </pre>
   *
   * <code>.event_logging.v4.MultiObjectComplexType before = 1 [json_name = "before"];</code>
   * @return Whether the before field is set.
   */
  boolean hasBefore();
  /**
   * <pre>
   * Describes the state of one or more object properties before it was changed.
   * </pre>
   *
   * <code>.event_logging.v4.MultiObjectComplexType before = 1 [json_name = "before"];</code>
   * @return The before.
   */
  uk.gov.gchq.event_logging.v4.MultiObjectComplexType getBefore();
  /**
   * <pre>
   * Describes the state of one or more object properties before it was changed.
   * </pre>
   *
   * <code>.event_logging.v4.MultiObjectComplexType before = 1 [json_name = "before"];</code>
   */
  uk.gov.gchq.event_logging.v4.MultiObjectComplexTypeOrBuilder getBeforeOrBuilder();

  /**
   * <pre>
   * Describes the state of one or more object properties after it was changed.
   * </pre>
   *
   * <code>.event_logging.v4.MultiObjectComplexType after = 2 [json_name = "after", (.buf.validate.field) = { ... }</code>
   * @return Whether the after field is set.
   */
  boolean hasAfter();
  /**
   * <pre>
   * Describes the state of one or more object properties after it was changed.
   * </pre>
   *
   * <code>.event_logging.v4.MultiObjectComplexType after = 2 [json_name = "after", (.buf.validate.field) = { ... }</code>
   * @return The after.
   */
  uk.gov.gchq.event_logging.v4.MultiObjectComplexType getAfter();
  /**
   * <pre>
   * Describes the state of one or more object properties after it was changed.
   * </pre>
   *
   * <code>.event_logging.v4.MultiObjectComplexType after = 2 [json_name = "after", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.MultiObjectComplexTypeOrBuilder getAfterOrBuilder();

  /**
   * <pre>
   * Used to determine if the action was successful. If omitted it is assumed that the event was successful and was permitted.
   * </pre>
   *
   * <code>.event_logging.v4.OutcomeComplexType outcome = 3 [json_name = "outcome"];</code>
   * @return Whether the outcome field is set.
   */
  boolean hasOutcome();
  /**
   * <pre>
   * Used to determine if the action was successful. If omitted it is assumed that the event was successful and was permitted.
   * </pre>
   *
   * <code>.event_logging.v4.OutcomeComplexType outcome = 3 [json_name = "outcome"];</code>
   * @return The outcome.
   */
  uk.gov.gchq.event_logging.v4.OutcomeComplexType getOutcome();
  /**
   * <pre>
   * Used to determine if the action was successful. If omitted it is assumed that the event was successful and was permitted.
   * </pre>
   *
   * <code>.event_logging.v4.OutcomeComplexType outcome = 3 [json_name = "outcome"];</code>
   */
  uk.gov.gchq.event_logging.v4.OutcomeComplexTypeOrBuilder getOutcomeOrBuilder();

  /**
   * <pre>
   * Any other event data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 4 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<uk.gov.gchq.event_logging.v4.DataComplexType> 
      getDataList();
  /**
   * <pre>
   * Any other event data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 4 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.DataComplexType getData(int index);
  /**
   * <pre>
   * Any other event data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 4 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  int getDataCount();
  /**
   * <pre>
   * Any other event data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 4 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<? extends uk.gov.gchq.event_logging.v4.DataComplexTypeOrBuilder> 
      getDataOrBuilderList();
  /**
   * <pre>
   * Any other event data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 4 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.DataComplexTypeOrBuilder getDataOrBuilder(
      int index);
}
