// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/user_details_complex_type.proto

// Protobuf Java Version: 4.26.1
package uk.gov.gchq.event_logging.v4;

public interface UserDetailsComplexTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event_logging.v4.UserDetailsComplexType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A unique identifier used across the business to identify this person.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * A unique identifier used across the business to identify this person.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * A person's staff number.
   * </pre>
   *
   * <code>string staff_number = 2 [json_name = "staffNumber"];</code>
   * @return The staffNumber.
   */
  java.lang.String getStaffNumber();
  /**
   * <pre>
   * A person's staff number.
   * </pre>
   *
   * <code>string staff_number = 2 [json_name = "staffNumber"];</code>
   * @return The bytes for staffNumber.
   */
  com.google.protobuf.ByteString
      getStaffNumberBytes();

  /**
   * <pre>
   * The person's surname.
   * </pre>
   *
   * <code>string surname = 3 [json_name = "surname"];</code>
   * @return The surname.
   */
  java.lang.String getSurname();
  /**
   * <pre>
   * The person's surname.
   * </pre>
   *
   * <code>string surname = 3 [json_name = "surname"];</code>
   * @return The bytes for surname.
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <pre>
   * The person's initials.
   * </pre>
   *
   * <code>string initials = 4 [json_name = "initials"];</code>
   * @return The initials.
   */
  java.lang.String getInitials();
  /**
   * <pre>
   * The person's initials.
   * </pre>
   *
   * <code>string initials = 4 [json_name = "initials"];</code>
   * @return The bytes for initials.
   */
  com.google.protobuf.ByteString
      getInitialsBytes();

  /**
   * <pre>
   * The person's title.
   * </pre>
   *
   * <code>string title = 5 [json_name = "title"];</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * The person's title.
   * </pre>
   *
   * <code>string title = 5 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * The person's given name. If a preferred name also exists then use KnownAs for this preferred name, otherwise use the same name for both elements.
   * </pre>
   *
   * <code>string given_name = 6 [json_name = "givenName"];</code>
   * @return The givenName.
   */
  java.lang.String getGivenName();
  /**
   * <pre>
   * The person's given name. If a preferred name also exists then use KnownAs for this preferred name, otherwise use the same name for both elements.
   * </pre>
   *
   * <code>string given_name = 6 [json_name = "givenName"];</code>
   * @return The bytes for givenName.
   */
  com.google.protobuf.ByteString
      getGivenNameBytes();

  /**
   * <pre>
   * The name that this person is known as.
   * </pre>
   *
   * <code>string known_as = 7 [json_name = "knownAs"];</code>
   * @return The knownAs.
   */
  java.lang.String getKnownAs();
  /**
   * <pre>
   * The name that this person is known as.
   * </pre>
   *
   * <code>string known_as = 7 [json_name = "knownAs"];</code>
   * @return The bytes for knownAs.
   */
  com.google.protobuf.ByteString
      getKnownAsBytes();

  /**
   * <pre>
   * Is the person an employee or a contractor.
   * </pre>
   *
   * <code>string person_type = 8 [json_name = "personType"];</code>
   * @return The personType.
   */
  java.lang.String getPersonType();
  /**
   * <pre>
   * Is the person an employee or a contractor.
   * </pre>
   *
   * <code>string person_type = 8 [json_name = "personType"];</code>
   * @return The bytes for personType.
   */
  com.google.protobuf.ByteString
      getPersonTypeBytes();

  /**
   * <pre>
   * The business group.
   * </pre>
   *
   * <code>string group = 9 [json_name = "group"];</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <pre>
   * The business group.
   * </pre>
   *
   * <code>string group = 9 [json_name = "group"];</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <pre>
   * The business unit within the business group.
   * </pre>
   *
   * <code>string unit = 10 [json_name = "unit"];</code>
   * @return The unit.
   */
  java.lang.String getUnit();
  /**
   * <pre>
   * The business unit within the business group.
   * </pre>
   *
   * <code>string unit = 10 [json_name = "unit"];</code>
   * @return The bytes for unit.
   */
  com.google.protobuf.ByteString
      getUnitBytes();

  /**
   * <pre>
   * The position within the business unit.
   * </pre>
   *
   * <code>string position = 11 [json_name = "position"];</code>
   * @return The position.
   */
  java.lang.String getPosition();
  /**
   * <pre>
   * The position within the business unit.
   * </pre>
   *
   * <code>string position = 11 [json_name = "position"];</code>
   * @return The bytes for position.
   */
  com.google.protobuf.ByteString
      getPositionBytes();

  /**
   * <pre>
   * The role that the person is in.
   * </pre>
   *
   * <code>string role = 12 [json_name = "role"];</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <pre>
   * The role that the person is in.
   * </pre>
   *
   * <code>string role = 12 [json_name = "role"];</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <pre>
   * The grade required for the current post.
   * </pre>
   *
   * <code>string grade_of_post = 13 [json_name = "gradeOfPost"];</code>
   * @return The gradeOfPost.
   */
  java.lang.String getGradeOfPost();
  /**
   * <pre>
   * The grade required for the current post.
   * </pre>
   *
   * <code>string grade_of_post = 13 [json_name = "gradeOfPost"];</code>
   * @return The bytes for gradeOfPost.
   */
  com.google.protobuf.ByteString
      getGradeOfPostBytes();

  /**
   * <pre>
   * Is the person full-time, part-time etc.
   * </pre>
   *
   * <code>string employment_type = 14 [json_name = "employmentType"];</code>
   * @return The employmentType.
   */
  java.lang.String getEmploymentType();
  /**
   * <pre>
   * Is the person full-time, part-time etc.
   * </pre>
   *
   * <code>string employment_type = 14 [json_name = "employmentType"];</code>
   * @return The bytes for employmentType.
   */
  com.google.protobuf.ByteString
      getEmploymentTypeBytes();

  /**
   * <pre>
   * The employment status of the person, e.g. Active, Retired, Maternity Leave, Sabbatical Leave, etc.
   * </pre>
   *
   * <code>string employment_status = 15 [json_name = "employmentStatus"];</code>
   * @return The employmentStatus.
   */
  java.lang.String getEmploymentStatus();
  /**
   * <pre>
   * The employment status of the person, e.g. Active, Retired, Maternity Leave, Sabbatical Leave, etc.
   * </pre>
   *
   * <code>string employment_status = 15 [json_name = "employmentStatus"];</code>
   * @return The bytes for employmentStatus.
   */
  com.google.protobuf.ByteString
      getEmploymentStatusBytes();

  /**
   * <pre>
   * The person's nationality.
   * </pre>
   *
   * <code>string nationality = 16 [json_name = "nationality"];</code>
   * @return The nationality.
   */
  java.lang.String getNationality();
  /**
   * <pre>
   * The person's nationality.
   * </pre>
   *
   * <code>string nationality = 16 [json_name = "nationality"];</code>
   * @return The bytes for nationality.
   */
  com.google.protobuf.ByteString
      getNationalityBytes();

  /**
   * <pre>
   * The building that the person usually works in.
   * </pre>
   *
   * <code>string location = 17 [json_name = "location"];</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <pre>
   * The building that the person usually works in.
   * </pre>
   *
   * <code>string location = 17 [json_name = "location"];</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <pre>
   * The room number or name that the person usually works in.
   * </pre>
   *
   * <code>string room_number = 18 [json_name = "roomNumber"];</code>
   * @return The roomNumber.
   */
  java.lang.String getRoomNumber();
  /**
   * <pre>
   * The room number or name that the person usually works in.
   * </pre>
   *
   * <code>string room_number = 18 [json_name = "roomNumber"];</code>
   * @return The bytes for roomNumber.
   */
  com.google.protobuf.ByteString
      getRoomNumberBytes();

  /**
   * <pre>
   * The person's primary or internal phone number or extension.
   * </pre>
   *
   * <code>string phone = 19 [json_name = "phone"];</code>
   * @return The phone.
   */
  java.lang.String getPhone();
  /**
   * <pre>
   * The person's primary or internal phone number or extension.
   * </pre>
   *
   * <code>string phone = 19 [json_name = "phone"];</code>
   * @return The bytes for phone.
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <pre>
   * The person's secondary phone number or extension.
   * </pre>
   *
   * <code>string secondary_phone = 20 [json_name = "secondaryPhone"];</code>
   * @return The secondaryPhone.
   */
  java.lang.String getSecondaryPhone();
  /**
   * <pre>
   * The person's secondary phone number or extension.
   * </pre>
   *
   * <code>string secondary_phone = 20 [json_name = "secondaryPhone"];</code>
   * @return The bytes for secondaryPhone.
   */
  com.google.protobuf.ByteString
      getSecondaryPhoneBytes();

  /**
   * <pre>
   * The staff number of the person's supervisor or line manager.
   * </pre>
   *
   * <code>string supervisor_staff_number = 21 [json_name = "supervisorStaffNumber"];</code>
   * @return The supervisorStaffNumber.
   */
  java.lang.String getSupervisorStaffNumber();
  /**
   * <pre>
   * The staff number of the person's supervisor or line manager.
   * </pre>
   *
   * <code>string supervisor_staff_number = 21 [json_name = "supervisorStaffNumber"];</code>
   * @return The bytes for supervisorStaffNumber.
   */
  com.google.protobuf.ByteString
      getSupervisorStaffNumberBytes();

  /**
   * <pre>
   * When this person's current position is scheduled to end, e.g. the end date of a fixed term employment contract.
   * </pre>
   *
   * <code>uint32 occupancy_end_date = 22 [json_name = "occupancyEndDate"];</code>
   * @return The occupancyEndDate.
   */
  int getOccupancyEndDate();

  /**
   * <pre>
   * Describes a person's main employing organisation irrespective of who they are contracted or seconded to, or are performing an internship with.
   * </pre>
   *
   * <code>string organisation = 23 [json_name = "organisation"];</code>
   * @return The organisation.
   */
  java.lang.String getOrganisation();
  /**
   * <pre>
   * Describes a person's main employing organisation irrespective of who they are contracted or seconded to, or are performing an internship with.
   * </pre>
   *
   * <code>string organisation = 23 [json_name = "organisation"];</code>
   * @return The bytes for organisation.
   */
  com.google.protobuf.ByteString
      getOrganisationBytes();

  /**
   * <pre>
   * Describes which organisation is currently hosting a person if they are on secondment, internship or are contracted to work for.
   * </pre>
   *
   * <code>string host_organisation = 24 [json_name = "hostOrganisation"];</code>
   * @return The hostOrganisation.
   */
  java.lang.String getHostOrganisation();
  /**
   * <pre>
   * Describes which organisation is currently hosting a person if they are on secondment, internship or are contracted to work for.
   * </pre>
   *
   * <code>string host_organisation = 24 [json_name = "hostOrganisation"];</code>
   * @return The bytes for hostOrganisation.
   */
  com.google.protobuf.ByteString
      getHostOrganisationBytes();

  /**
   * <pre>
   * Any other user data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 25 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<uk.gov.gchq.event_logging.v4.DataComplexType> 
      getDataList();
  /**
   * <pre>
   * Any other user data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 25 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.DataComplexType getData(int index);
  /**
   * <pre>
   * Any other user data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 25 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  int getDataCount();
  /**
   * <pre>
   * Any other user data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 25 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<? extends uk.gov.gchq.event_logging.v4.DataComplexTypeOrBuilder> 
      getDataOrBuilderList();
  /**
   * <pre>
   * Any other user data that does not fit into a schema element but may be useful for the purpose of audit.
   * </pre>
   *
   * <code>repeated .event_logging.v4.DataComplexType data = 25 [json_name = "data", (.buf.validate.field) = { ... }</code>
   */
  uk.gov.gchq.event_logging.v4.DataComplexTypeOrBuilder getDataOrBuilder(
      int index);
}
