// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_logging/v4/virtual_session_session_state_simple_type.proto

// Protobuf Java Version: 4.26.1
package uk.gov.gchq.event_logging.v4;

/**
 * <pre>
 * Describes the state of a virtual session when viewing another user's session, e.g. screen sharing or remote assistance type activities.
 * </pre>
 *
 * Protobuf enum {@code event_logging.v4.VirtualSessionSessionStateSimpleType}
 */
public enum VirtualSessionSessionStateSimpleType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default
   * </pre>
   *
   * <code>VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_UNSPECIFIED = 0;</code>
   */
  VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_UNSPECIFIED(0),
  /**
   * <code>VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_PARKED = 1;</code>
   */
  VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_PARKED(1),
  /**
   * <code>VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_UNPARKED = 2;</code>
   */
  VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_UNPARKED(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      VirtualSessionSessionStateSimpleType.class.getName());
  }
  /**
   * <pre>
   * Default
   * </pre>
   *
   * <code>VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_PARKED = 1;</code>
   */
  public static final int VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_PARKED_VALUE = 1;
  /**
   * <code>VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_UNPARKED = 2;</code>
   */
  public static final int VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_UNPARKED_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static VirtualSessionSessionStateSimpleType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static VirtualSessionSessionStateSimpleType forNumber(int value) {
    switch (value) {
      case 0: return VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_UNSPECIFIED;
      case 1: return VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_PARKED;
      case 2: return VIRTUAL_SESSION_SESSION_STATE_SIMPLE_TYPE_UNPARKED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<VirtualSessionSessionStateSimpleType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      VirtualSessionSessionStateSimpleType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<VirtualSessionSessionStateSimpleType>() {
          public VirtualSessionSessionStateSimpleType findValueByNumber(int number) {
            return VirtualSessionSessionStateSimpleType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return uk.gov.gchq.event_logging.v4.VirtualSessionSessionStateSimpleTypeProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final VirtualSessionSessionStateSimpleType[] VALUES = values();

  public static VirtualSessionSessionStateSimpleType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private VirtualSessionSessionStateSimpleType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:event_logging.v4.VirtualSessionSessionStateSimpleType)
}

